---
language: go
go:
- tip
- "1.9"
- "1.8"
- "1.7"
- "1.6"
- "1.5"
- "1.4"
- "1.3"
- "1.2"
- "1.1"
# Travis is broken: for "1.0" it launches with go 1.7.4
# https://travis-ci.org/dolmen-go/hexenc/jobs/342255514
# - "1.0"

go_import_path: github.com/dolmen-go/hexenc

before_install:
- go list
# "go get" supports "-t" only from go1.2
- go get $( [[ `go version` != *' go1.1 '* ]] && echo "-t" ) -v ./...

script:
- go test -coverprofile=coverage.txt -covermode=atomic
# If go >= 1.10, also test my own encoder
- "if [[ `go version` = *' go1.'[0-9][^.\\ ]' '* ]]; then go test -tags builtinencoder; fi"

after_success:
- bash <(curl -s https://codecov.io/bash)
